### ISSUE TITLE
Open in xCode action for a plugin project doesn't work

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1373]
## Steps to Reproduce

1. Start IDEA with the M18 RC plugin installed
1. File > New Project, select Plugin type, and Next
1. After IDEA has initialised, right-click the root node in the project view and select Flutter > Open in xCode

Actual result: xCode starts, but the plugin code isn't available

Expected result: xCode opens, the plugincode is available for running, and the Run button starts the plugin example app as per:
https://flutter.io/developing-packages/#step-2c-add-ios-platform-code-hmswift

**Comment by mit-mit** [comment]
I think it's opening `./plugin-name/Runner.xcodeproj`? It should be opening `./plugin-name/example/ios/Runner.xcworkspace`.

**Comment by mit-mit** [comment]
cc @devoncarew

**Comment by mit-mit** [comment]
Confirmed after feedback from @stevemessick that this works if you do a Run in IDEA prior to opening in xCode. Removing M18 blocking status.

**Comment by stevemessick** [comment]
AI: Figure out a good UX to ensure a build is done prior to launching the other IDE. You may need to do a build prior to every launch, but that is time-consuming and it would be nice to not have to do it unless needed.

**Comment by pq** [comment]
@mit-mit: #1527 updates our logic to open `Runner.xcworkspace`.  I believe this should be fixed?

**Comment by mit-mit** [comment]
No, it still fails if you open xCode prior to doing a built in IJ:

```
/Users/mit/tmp/untitled4/example/ios/Runner/GeneratedPluginRegistrant.m:6:9: 'untitled4/Untitled4Plugin.h' file not found
```

I think the best solution might be to do a build in IJ as part of project creation?

**Comment by pq** [comment]
Ah, OK.  I like the idea of volunteering to run a build before opening.

What's the best resource to look for as a sentinel?

/cc @cbracken

**Comment by pq** [comment]
@cbracken, @szakarias  : could you advise on a sentinel resource to look for to indicate that an xcode build should (not) be performed?

**Comment by pq** [comment]
@cbracken: any ideas on this one?

**Comment by cbracken** [comment]
The ideal would be to always perform the build but Flutter should be smart enough to turn that into a no-op if everything that needs building is already built. I suspect that that's not yet feasible though it seems like something we should open a bug for.

In the meantime, the presence of a `build/ios` directory might be a sort-of-dodgy heuristic that an iOS build has been done (or at least attempted) at least once. It might be ages out-of-date, but if this is specific to newly-created projects, it's probably sufficient. I'd certainly put a big TODO on that code though :)
