### ISSUE TITLE
Device connection dies on hot reload when using Dart 2 preview

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1809]
With IntelliJ IDEA 2017.3.4 (Community Edition) on Windows, and a very recent flutter:
```
Flutter 0.1.5-pre.9 • channel master • git@github.com:flutter/flutter.git
Framework • revision 21c514fc56 (29 hours ago) • 2018-02-22 10:11:09 +0100
```

## Steps to Reproduce

1. Enable dart 2 preview mode
1. Restart IJ
1. Create new project
1. Start an Android Emulator
1. Run project
1. Make a small change
1. Hot reload

```
Initializing hot reload...
D/        ( 5675): HostConnection::get() New Host Connection established 0xab1884c0, tid 5692
Lost connection to device.
```

**Comment by jacob314** [comment]
Can you repro using `flutter run` instead of intellij?

**Comment by mit-mit** [comment]
I cannot

**Comment by mit-mit** [comment]
Ah, wait, I also can only repro if I have dart-2-preview on! Updated repro steps at the top!

**Comment by jacob314** [comment]
Can you run flutter with the --verbose flag to get a bit more detail on what is happening?
One other idea is to remove your `build` directory and any dill files that are lying around outside it and rerun. In the past I've had issues where old kernel files in my build directory caused failures on reload.

`find -name "*.dill"`
With a newer version of the flutter repo, dill files will only be in the build directory but that only changed in `master` a few days ago.

**Comment by mit-mit** [comment]
cc @devoncarew did anyone else see if they hit this on Windows?

**Comment by devoncarew** [comment]
I can't repro this on the mac on the latest flutter. You're seeing this on windows, both from IntelliJ w/ --preview-dart-2, and from the cli w/ --preview-dart-2?

@DanTup, you're testing on windows (for VSCode --preview-dart-2) looked good?

**Comment by jacob314** [comment]
See the repro steps for https://github.com/flutter/flutter/issues/14847 I just filed.
To reproduce I expect you need to sync an older flutter build, call flutter run with --preview-dart-2 then sync to the latest flutter build and run with --preview-dart-2.  The old dill files will get loaded and you will get strange crashes if the dill files are not compatible.

**Comment by devoncarew** [comment]
Ah, ok. Closing in favor of https://github.com/flutter/flutter/issues/14847.

**Comment by mit-mit** [comment]
Great, @jacob314 that sounds about right for what I might have done!

**Comment by grindvoll** [comment]
I experience exactly the same problem. Hot reload from IDEA always generate an error when using `--preview-dart-2`. The problem occurs when creating a new project with the latest flutter version (e.g. no `*.dill` files from previous builds are present). So it seems that it's not the same problem as described in flutter/flutter#14847.  From the command line, hot reload works fine. The error message in the IDEA console is:

```
Initializing hot reload...
D/        ( 9182): HostConnection::get() New Host Connection established 0xde19e400, tid 9206
Lost connection to device.
```

Testing is done on Windows using version 22.0.2 of the Flutter plugin and the following flutter version:

```
Flutter 0.1.6-pre.7 • channel master • https://github.com/flutter/flutter.git
Framework • revision c3bbcb6f91 (2 days ago) • 2018-02-24 09:28:58 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

```

**Comment by DanTup** [comment]
@devoncarew 

> @DanTup, you're testing on windows (for VSCode --preview-dart-2) looked good?

Didn't respond to this sooner as it was marked as a dupe, but to confirm I have not seen issues like this from Dart Code on Windows in the (admittedly limited) testing I've done. Just did some testing again now with the gallery app and other than first hot reload being very slow (reloaded 544 of 560 libraryes taking 8 seconds?!) I didn't have any issues.

**Comment by DanTup** [comment]
Had this come in this morning:

https://github.com/Dart-Code/Dart-Code/issues/625

**Comment by jacob314** [comment]
I'm landing 
https://github.com/flutter/flutter/pull/14994
which catches some issues where preview-dart-2 and track-widget-creation weren't quite plumbed through correctly for various flavors of flutter_tools.

**Comment by DanTup** [comment]
I suspect this probably deals with https://github.com/flutter/flutter/issues/14945 too?

**Comment by jacob314** [comment]
Likely related but I'm not positive. I'm more puzzled by how things could ever work with an IDE without my change. One theory is the VM can actually chug along with a mixture of dart1 and dart2 data as long as there isn't anything in the apis that is incompatible between dart 1 and dart 2.

**Comment by jacob314** [comment]
Fyi this might also be fixed by https://github.com/flutter/engine/pull/4733

**Comment by jornvandebeek** [comment]
Unfortunately, can confirm on master channel as of today (with the referenced issues/PRs merged) this issue still occurs, Even after a `flutter clean`, `flutter ide-config` and an Android Studio restart
```
PS D:\AndroidStudioProjects\fzzz> flutter doctor -v
[√] Flutter (Channel master, v0.1.8-pre.32, on Microsoft Windows [Version 10.0.16299.248], locale nl-NL)
    • Flutter version 0.1.8-pre.32 at D:\flutter
    • Framework revision 73a1a74ba1 (11 hours ago), 2018-03-01 18:34:15 -0800
    • Engine revision 269bab73b6
    • Dart version 2.0.0-dev.31.0.flutter-1aaebedd70

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\androidsdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\androidsdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```
As others noted, `flutter run` hot reload works fine.
