### ISSUE TITLE
[web]: <Problem with emulator on Android Studio, show Loading...., when beta channel>

### ISSUE THREAD

**Issue by abedputra** [flutter/flutter-intellij#4632]
I have installed flutter with a stable version, and all working well. But when developing for the web I following [this doc](https://flutter.dev/docs/get-started/web) and change to the beta channel, my Android Studio emulator show "loading....."
![Screen Shot 2020-06-17 at 09 30 13](https://user-images.githubusercontent.com/11581453/84844550-31230280-b07d-11ea-99e5-9906e9ad40c0.png)

but when I run `flutter devices` its detect 3 devices
`Redmi Note 4 • 22efde9e9904 • android-arm64  • Android 7.0 (API 24)`
`Web Server   • web-server   • web-javascript • Flutter Tools`
`Chrome       • chrome       • web-javascript • Google Chrome 83.0.4103.97`

this is the `flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

this is flutter version
```
Flutter 1.19.0-4.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision f994b76974 (7 days ago) • 2020-06-09 15:53:13 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)
```

I was wondering if we were on the beta channel the emulator would be like this?

**Comment by stevemessick** [comment]
Dup of #3892 (Which, for the record, was fixed and recently re-opened.)

Work-around is to restart the device daemon or re-open project w/o shutting down the IDE. A proper fix is currently WIP.

**Comment by abedputra** [comment]
Hi @stevemessick , Thank you, but I have tried restarting the daemon, or reopening as you said, but it's still not resolved.

Btw, this is the `flutter doctor -v`
```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-ID)
    • Flutter version 1.19.0-4.1.pre at /Users/abedputra/Development/flutter
    • Framework revision f994b76974 (8 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/abedputra/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

! Doctor found issues in 1 category.
```

**Comment by manishh** [comment]
Same problem, no fix despite restarting several times. :(

**Comment by stevemessick** [comment]
Fixed in #4633.

The [plugin dev channel ](https://github.com/flutter/flutter-intellij/wiki/Dev-Channel)update this weekend will include that fix.

It seems like everyone experiencing this issue is using the beta or master channel of the Flutter SDK. This problem was triggered by a change in the SDK, which #4633 solves.

**Comment by abedputra** [comment]
Thanks, I will wait for the update.

**Comment by anirudhsharma392** [comment]
I have literally reinstalled my Mac OS to resolve this issue.But still cannot fix it, now waiting for the next update.

**Comment by 029vaibhav** [comment]
I am facing the same issue. I have both android studio and intellij ultimate  but the problem still resides. Also i have tried the flutter plugin from dev channel but still no fix
