### ISSUE TITLE
Add Flutter SDK channel/version info to analytics

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/flutter-intellij#4901]
Could you report the version/channel of the Flutter SDK along with other information, when an event is recorded? I think it could be recorded as a part of `appInfo`.

**Comment by jayoung-lee** [comment]
The new custom dimension does not include channel information (stable/master/g3/...). Is it possible to add that?

**Comment by devoncarew** [comment]
Note to self: when we add this, we can report in the current flutter version field, using a format like `stable/1.20.4`, `master/1.19.0-5.0.pre`, ...

**Comment by devoncarew** [comment]
Bumping this portion of the change to the next release -

**Comment by stevemessick** [comment]
This may have been fixed recently.

**Comment by jayoung-lee** [comment]
Analytics is still not reporting the channel for some reason. Today's data is in this format: `1.9.1+hotfix.5`

**Comment by stevemessick** [comment]
This is going to take a bit of work. The only time analytics is called with a SDK is from console error logging code. All other calls do not include enough information to determine the SDK. We'll need to check each invocation to determine if it has a direct reference to the project (many do), and then use it to get the SDK. If it does not, the `AnActionEvent` that triggered the action has a reference to the project. That will need to be propagated down to the analytic invocation.

After all that there will still be some cases where we cannot get the project. So, sometimes the channel will not be included.

**Comment by jayoung-lee** [comment]
Got it. I could actually use `cd3` to identify a certain group of users I was interested in. Please feel free to deprioritize this if there's no other needs.

**Comment by stevemessick** [comment]
@devoncarew If @jayoung-lee is going to re-use `cd3` then should we stop writing that value? There's still time to get that change in M53 if we're quick. Or do you want to make these changes for other reasons?

**Comment by devoncarew** [comment]
Ah, a bit ago I'd started writing the value `bazel` to cd3 if any project in the workspace was using bazel. I think that means that the use case is satisfied, and we can close this issue?

https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/analytics/Analytics.java#L158

**Comment by jayoung-lee** [comment]
Yes, that use case is satisfied. I will close the issue.
