### ISSUE TITLE
Web: Breakpoint disabling impossible

### ISSUE THREAD

**Issue by Uni2K** [flutter/flutter-intellij#5128]
## Steps to Reproduce
1. Run Flutter Web in Intellij and create some breakpoints in the debugger
2. Wait for them to get hit (they wont get marked as detected ->so no little checkmark)
3. Disable the breakpoints (click on them so they disappear)
4. Hot reload -> they will still get hit

At this point it is impossible to run without the breakpoints, "disable all" is also not working. The only thing that works is manually restarting the entire application.

## Version info
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19041.685], locale de-DE)
    • Flutter version 1.25.0-8.1.pre at D:\Flutter
    • Framework revision 8f89f6505b (2 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at ///
    • Platform android-29, build-tools 29.0.2
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.1
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[√] VS Code (version 1.52.0)
    • VS Code at ///
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.60

! Doctor found issues in 1 category.

**Comment by helin24** [comment]
I was able to reproduce this problem. 

Observations:
- A breakpoint can be turned on and off successfully if the app isn't hot reloaded
- If a breakpoint is turned off and the app is hot reloaded, breakpoints work as expected afterwards (can be turned on and off)
- If a breakpoint is turned on and the app is hot reloaded, the red dot turns into the grey prohibition sign and the breakpoint can't be removed

**Comment by archie-sh** [comment]
It also happens for me, its super annoying. Hopefully someone picks it up.

**Comment by Ceschref** [comment]
I'm also have the same problem when I test Flutter2 on the Web. 😂😂😂. Maybe they're should resolve it.

**Comment by capce** [comment]
This seems not to be exclusive to Flutter web in Intellij. I also have this problem in VS Code.

**Comment by capce** [comment]
It seems to be a problem with the Chrome browser. The problem does not occur when I am using the Edge Browser!

**Comment by annagrin** [comment]
Fixed in dart-lang/webdev#1310

**Comment by vast00** [comment]
Why am I still facing this bug?

**Comment by matanshukry** [comment]
@annagrin I'm on latest IntelliJ and flutter, and this is still happening. As before - only seems to happen with web.

Flutter:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.19045.4170], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.2)
[√] Android Studio (version 2023.2)
[√] IntelliJ IDEA Community Edition (version 2023.3)
[√] VS Code, 64-bit edition (version 1.79.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

IntelliJ:
```
Android Studio Iguana | 2023.2.1 Patch 1
Build #AI-232.10300.40.2321.11567975, built on March 13, 2024
Runtime version: 17.0.9+0--11185874 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.marketplace (232.10300.41)
    Dart (232.10305)
    com.localizely.flutter-intl (1.18.4-2023.2)
    com.bloc.intellij_generator_plugin (4.0.0)
    cn.neday.excavator (2.4.5)
    pl.pszklarska.pubversionchecker (1.3.5)
    io.flutter (78.4.1)

```

**Comment by helin24** [comment]
@matanshukry it's been a while, so can you describe your case? You set breakpoints, disable them, then restart (what action are you taking to restart the app?), and breakpoints are still hit?

I believe @elliette is making upcoming changes for this across IDEs.

**Comment by matanshukry** [comment]
@helin24 I have the exact same issue as described in the original post.
For your question - no, I'm not restarting; as pointed out, restart is the only thing that makes the breakpoints "go away".

That is, if you try and disable a breakpoint when the debugger has stopped on it, it will then keeps stopping at that breakpoint, no matter what.

> At this point it is impossible to run without the breakpoints, "disable all" is also not working. The only thing that works is manually restarting the entire application.

**Comment by elliette** [comment]
This sounds the like the same issue as https://github.com/dart-lang/webdev/issues/2257

The fix will be in the next version of DWDS which I'm aiming to be on the Flutter master channel by end of this month.
