### ISSUE TITLE
Yesterday's update broke this plugin in multiple ways

### ISSUE THREAD

**Issue by aliakhtar** [flutter/flutter-intellij#5230]
## Steps to Reproduce

1) Try to create a new flutter project through File -> New Project. After completing the wizard you get an error that 'at least one platform must be selected' even though all fields were filled in.

2) Flutter inspector just fails with the following output for me:

![image](https://user-images.githubusercontent.com/5325112/106369979-e8079080-6377-11eb-86c7-d8a99543ed38.png)

## Version info

[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/ali/snap/flutter/common/flutter
    • Framework revision 9b2d32b605 (8 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ali/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/ali/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/ali/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

**Comment by EboMike** [comment]
I'm also seeing this problem with the 1.22.5 SDK, so the issue when creating a new project was presumably caused by the Flutter plug-in, which was just updated.
I'm seeing it with plugin version 53.0.2.

**Comment by ossama0808** [comment]
Same issue here, Flutter plugin version 53.0.5 using Intellij Idea.

**Comment by aliakhtar** [comment]
FYI you can manually revert back by downloading the last version and installing the zip.

**Comment by devoncarew** [comment]
Thanks for the reports! This was actually caused by https://github.com/flutter/devtools/issues/2653, which is now resolved.

**Comment by Polygeekism** [comment]
I just did a brand new install on windows
Flutter 1.22.6
Android SDK 30.0.3
IntelliJ 2020.1.4
And I am still getting the platform error.

**Comment by thepat1337** [comment]
I had the same issue. Manually installing this version fixed it for me.
https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/107560

Guess I'll wait a bit before updating :)

**Comment by timpelser** [comment]
> I had the same issue. Manually installing this version fixed it for me.
> https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/107560
> 
> Guess I'll wait a bit before updating :)

This fixed it. But means there is still an issue in 53.0.2.

**Comment by aliakhtar** [comment]
So, should I update or not?

**Comment by NZhlebinkov** [comment]
> I had the same issue. Manually installing this version fixed it for me.
> https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/107560
> 
> Guess I'll wait a bit before updating :)

After manually installing version 52.2.5 I get the error "Incompatible (since build 203.5981.155 > IU-201.8743.12)" and I no longer have the option to create a Flutter project in the menu.
Do I need to install another version of Flutter as well, and not only the plugin?

**Comment by Celesica** [comment]
Having similar issue on macOS. The "Platforms" are not showing up when creating a new project.

**Comment by roeniss** [comment]
Is this IntelliJ issue? As same as @Celesica, I can't create a new project anymore after updating my IntelliJ to 2021.3

**Comment by devoncarew** [comment]
@roeniss - can you open a new issue? This one was about a problem starting DevTools. We'd want to know the version of IntelliJ or Android Studio you're using, the version of the Flutter IntelliJ plugin, and the version of Flutter that you're on; thanks!

**Comment by echaelse** [comment]
Hi, I had the same problem on Intellij IDEA. I just reinstalled the flutter plugin and solve the problem, may be that works for you also.

**Comment by roeniss** [comment]
Thank you @echaelse! as devoncarew said, new patch was released so this issue is fixed now :)

**Comment by marvinvargasmachuca** [comment]
How can I update the plugin manually?

**Comment by roeniss** [comment]
@marvinvargasmachuca intellij -> preferences -> plugins tab -> flutter (installed tab) -> update -> restart IDE

**Comment by matheszabi** [comment]
Dec 15, 2022 I have the same problem :)
