### ISSUE TITLE
Full restart takes to the main.dart file after recent update. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#5231]
This issue started happening after I updated my Android Studio today. 

## Steps to Reproduce
1. Besides a regular `main.dart` file, create a new file say `home.dart`, and keep your cursor in that file. 
2. Do a full restart, you'll find the cursor is taken to the `main.dart` file. 

## Screenshot:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/40364434/106392602-e4fdb600-63f2-11eb-89c3-663a136f947f.gif)

## Version info

```
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.49.0)
```

**Comment by helin24** [comment]
@dark-chocolate I'm not able to reproduce this problem. Does it specifically occur when a new file is made, or does this also occur when you move to an already-existing file and restart? Also, does this occur when you close out of a project and reopen (instead of restarting IntelliJ entirely)?

You can also post your version info from `flutter doctor -v` so we can see some additional details.

**Comment by dark-chocolate** [comment]
@helin24 

> Does it specifically occur when a new file is made, or does this also occur when you move to an already-existing file and restart?

It occurs in both the cases. 

> Also, does this occur when you close out of a project and reopen (instead of restarting IntelliJ entirely)?

Yes, it does. I tried simple closing/restarting/clearing cache and what not, but the problem persist. It started happening since I upgraded my Android Studio. It's very frustrating to be honest.

**Comment by dark-chocolate** [comment]
I'm also seeing the same issue in my IntelliJ IDEA (upgraded it along with Android Studio but didn't run it since then), here's the version :

```
IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: com.ivanovych666.intellij.plugin.jsonsorter, Dart, io.flutter, org.jetbrains.kotlin
```

This simply means that there's no settings I tweaked accidentally; there might be something wrong with the updated IDEs or their Flutter equivalent updates.

**Comment by stevemessick** [comment]
@dark-chocolate What version of Dart and Flutter plugins are you using? In Android Studio and IntelliJ. As @helin24 mentioned, the output of `flutter version -v` (or in the IDE Tools>Flutter>Flutter Doctor) has everything we need.

**Comment by dark-chocolate** [comment]
@stevemessick I'm sorry I missed the last line of @helin24's message. 

Here's the full flutter doctor:

```
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-US)
    • Flutter version 1.25.0-8.0.pre at /Users/chocolate/Work/flutter
    • Framework revision a12e2a473a (8 weeks ago), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chocolate/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 86.0.4240.80

• No issues found!
```

**Comment by stevemessick** [comment]
@dark-chocolate Thanks for the update!

**Comment by stevemessick** [comment]
@dark-chocolate Which platform are you running the app on? I see you have macos and chrome available.

**Comment by dark-chocolate** [comment]
@stevemessick I ran the app on Android, iOS and macOS. All of them were behaving the same.

**Comment by stevemessick** [comment]
Thanks for all the info. Unfortunately, I still cannot reproduce the problem. I'm using the code from your screenshot. One difference is that I'm on Flutter's master channel. (My home network is very slow so I only keep master and stable.) Any chance you could switch to master and see if the problem persists?

Also, I can't see the icon of the button you click to do hot restart. Just to make sure we're talking about the same thing, could you add a screen shot of that button?

**Comment by dark-chocolate** [comment]
@stevemessick 

> Also, I can't see the icon of the button you click to do hot restart. Just to make sure we're talking about the same thing, could you add a screen shot of that button?

I'm sorry I didn't get that. The icon is the full restart green colored button, isn't it? 

![image](https://user-images.githubusercontent.com/40364434/106717055-75104b00-65ff-11eb-8111-1295733e2a2c.png)

So, I upgraded to the master channel, but the problem persist.

### Screenshot
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/40364434/106721078-7b54f600-6604-11eb-96e2-55ecd1ebfa10.gif)

### Flutter doctor:
```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.156, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-US)
    • Flutter version 1.26.0-18.0.pre.156 at /Users/chocolate/Work/flutter
    • Framework revision 45508985b1 (5 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chocolate/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 86.0.4240.80
```

**Comment by stevemessick** [comment]
> The icon is the full restart green colored button, isn't it?

Actually, that is the `Run` button. The hot restart button is located in
the Debugger tool window. It looks kinda like a rounded rectangle with an
arrow in the top section, and has an orange line IIRC (middle of the night
for me, no IDE handy to check). I'm not sure why clicking `Run` would shift
focus to main.dart. But it is doing an entirely different thing than hot
restart. The hot restart button has hover text that shows "Hot Restart"
IIRC; you could try to find that one then click it to see if it shifts
focus for you.

**Comment by Uni2K** [comment]
Same problem here. It does not need a full restart, a hot-restart is enough to trigger this. The issue occured first after the recent flutter update.

**Comment by dark-chocolate** [comment]
@stevemessick 

> (middle of the night for me, no IDE handy to check)

You've my respect!!! 
I found the "hot restart" button in the debugger tool window, and clicking it does the same thing, it puts the cursor on the `MaterialApp` widget in the `main.dart` file. Only "hot reload" seems to work. 

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/40364434/106740542-d8f43d00-661a-11eb-8750-009a92bcc8d8.gif)


@Uni2K Make sure to upvote this issue.

**Comment by Uni2K** [comment]
> 
> 
> @stevemessick
> 
> > (middle of the night for me, no IDE handy to check)
> 
> You've my respect!!!
> I found the "hot restart" button in the debugger tool window, and clicking it does the same thing, it puts the cursor on the `MaterialApp` widget in the `main.dart` file. Only "hot reload" seems to work.
> 
> ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/40364434/106740542-d8f43d00-661a-11eb-8750-009a92bcc8d8.gif)
> 
> @Uni2K Make sure to upvote this issue.

Weird, I got the same behaviour with hot reload too. It also automatically opens main.dart if its not already open.

**Comment by dark-chocolate** [comment]
@Uni2K You forgot to upvote the issue. I'm not getting any kind of reputation if you do or don't upvote it. But if you do upvote, the community will pay more attention to it.

**Comment by stea1thbear** [comment]
Same issue here, started after upgrading to Android Studio 4.1.2. Upvoted for visibility.

**Comment by devoncarew** [comment]
Thanks for the report! I can reproduce this.

**Comment by dark-chocolate** [comment]
@devoncarew Thankfully one of the members were able to reproduce the bug. It's more likely to get resolved now fast!

**Comment by devoncarew** [comment]
It looks like the Flutter Inspector tab is selecting the app's main widget after a restart, and that that is changing the file and selection of the active editor.

**Comment by Uni2K** [comment]
> 
> 
> @Uni2K You forgot to upvote the issue. I'm not getting any kind of reputation if you do or don't upvote it. But if you do upvote, the community will pay more attention to it.

Sorry, could not find the upvote button, still not finding it. :(

**Comment by devoncarew** [comment]
This should be addressed by https://github.com/flutter/devtools/pull/2675.

**Comment by jacob314** [comment]
Sorry about this. The devtools fix has landed and a new version of devtools has been published (0.9.7+3). If you have intellij open, you will need to close your project and reopen it to get the fix.
