### ISSUE TITLE
UnsupportedRenderingModeException error

### ISSUE THREAD

**Issue by DanMossa** [flutter/flutter-intellij#5376]
## What happened

I clicked the debug button on the top to run my flutter app in debug mode

## Version information

IntelliJ IDEA `2021.1` • Flutter plugin `io.flutter 55.0.5` • Dart plugin `211.6693.108`

Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (6 days ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2

## Exception

null

```
java.lang.NoClassDefFoundError: com/teamdev/jxbrowser/browser/UnsupportedRenderingModeException
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:676)
	at io.flutter.view.FlutterView.lambda$debugActive$5(FlutterView.java:447)
	at io.flutter.utils.AsyncUtils.lambda$whenCompleteUiThread$0(AsyncUtils.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.teamdev.jxbrowser.browser.UnsupportedRenderingModeException PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.1/plugins/flutter-intellij, version=55.0.5, package=null), packagePrefix=null, instanceId=91, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 32 more
```

**Comment by helin24** [comment]
@DanMossa thanks for this report. Could you follow these steps so I can gather some more information?
1. Uninstall the Flutter plugin (Preferences > Plugins, then click on Flutter) and restart
<img width="594" alt="Screen Shot 2021-04-07 at 6 36 27 PM" src="https://user-images.githubusercontent.com/6379305/113955266-3dc14480-97d0-11eb-9267-7903d5cb797b.png">

2. Reinstall the Flutter plugin (same area, can search for Flutter in marketplace) and restart
3. Follow the same steps as you listed to debug your app.
4. Go to the log file in Help > Show log in finder. There should be a file called `idea.log` - attach that here or let me know if you need a private channel to send it.

**Comment by helin24** [comment]
For anyone having this problem, could you post your operating system and version, and follow the [instructions above](https://github.com/flutter/flutter-intellij/issues/5376#issuecomment-815384003) to provide your logs?

**Comment by Reppinger** [comment]
> For anyone having this problem, could you post your operating system and version, and follow the [instructions above](https://github.com/flutter/flutter-intellij/issues/5376#issuecomment-815384003) to provide your logs?

I have a log, Helin. It is 3 MB. Hard for me to tell if I really want it here publicly.  :)  Do you have a private channel I can send it through?

**Comment by helin24** [comment]
> I have a log, @helin24. It is 3 MB. Hard for me to tell if I really want it here publicly. :) Do you have a private channel I can send it through?

Ah great! Could you email to helinx@google.com?

**Comment by Reppinger** [comment]
> > I have a log, @helin24. It is 3 MB. Hard for me to tell if I really want it here publicly. :) Do you have a private channel I can send it through?
> 
> Ah great! Could you email to [helinx@google.com](mailto:helinx@google.com)?

Sent!

**Comment by Reppinger** [comment]
@helin24, my MacOS version is 11.2.3

**Comment by Sagaris** [comment]
macOS 10.15.7

**Comment by Reppinger** [comment]
I just updated the flutter plugin in Intellij to v55.1.5 and it seems like the problem is fixed? Anyone else?

**Comment by helin24** [comment]
> I just updated the Flutter plugin in Intellij to v55.1.5 and it seems like the problem is fixed? Anyone else?

Yes! Thanks for noticing. The problem is not quite fixed, as we are simply not supporting using the embedded browser if it gives an error, but you should stop getting the annoying error messages!

I'm going to keep this issue open because we still want to figure out and fix the cause of the error.

**Comment by helin24** [comment]
https://github.com/flutter/flutter-intellij/pull/5453 should fix this problem.
