### ISSUE TITLE
Update plugin to IntelliJ 2021.3

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter-intellij#5872]
I'm not sure this is known, but the Flutter plugin is incompatible with the latest IntelliJ version (2021.3) which was released this week.

**Comment by cdprete** [comment]
I was about to report the same.
More details:
```
IntelliJ IDEA 2021.3 (Community Edition)
Build #IC-213.5744.223, built on November 27, 2021
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19044.1387], locale it-CH)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
```

**Comment by hunterino** [comment]
I just upgraded to 2021.3 Ultimate on Intel Mac, and I get the following error in the Event Log:

`2:07 PM	Plugin error: Plugin 'Flutter' (version '62.0.3') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-213.5744.223`

**Comment by shinayser** [comment]
Someone help! Just upgraded my IDE and having this exacly same problem:
![image](https://user-images.githubusercontent.com/1146982/144129744-eacd1f64-6204-410f-99e1-af550f85f016.png)

**Comment by bernaferrari** [comment]
You need to downgrade @shinayser

**Comment by eestein** [comment]
Man... what a bummer... thought this was gonna be a smooth update and then bam!

@bernaferrari do you know if there's a way to downgrade from the IDE? Or only downloading 2021.2?

**Comment by bernaferrari** [comment]
@eestein just open toolbox and click on downgrade. One click, there is no download needed.

**Comment by cjstehno** [comment]
Any idea of the timeline for fixing this?

**Comment by cyberpwnn** [comment]
A timeline would be much appreciated.

**Comment by devoncarew** [comment]
cc'ing @stevemessick so he's aware

**Comment by Justin42** [comment]
I think this is fixed by #5875 
Everything seems fine now.

**Comment by cjstehno** [comment]
I am still seeing the IntelliJ error:

> Plugin 'Flutter' (version '62.0.3') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-213.5744.223

When should we expect the fix to be in a published release?

**Comment by bernaferrari** [comment]
It is. Settings -> Plugin -> Update All

**Comment by cjstehno** [comment]
I must have updated too soon. I was able to download the updated version. Thanks.

**Comment by rdehuyss** [comment]
Can it be that this issue still exists?

I'm running:
- Intellij Ultimate 2021.3 Build #IU-213.5744.223, built on November 27, 2021
- Flutter plugin 63.0.5
- Dart plugin 213.5744.122
- Flutter -v output:
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (8 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```
When I run flutter doctor from the Intellij terminal, I get the following for Intellij IDEA ultimate edition:

```
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)

```

I cannot update any plugins anymore in Intellij, all plugins are up-to-date.

**Comment by bernaferrari** [comment]
No, this was fixed.

**Comment by AntoniosValais** [comment]
> Can it be that this issue still exists?
> 
> I'm running:
> 
>     * Intellij Ultimate 2021.3 Build #IU-213.5744.223, built on November 27, 2021
> 
>     * Flutter plugin 63.0.5
> 
>     * Dart plugin 213.5744.122
> 
>     * Flutter -v output:
> 
> 
> ```
> Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 18116933e7 (8 weeks ago) • 2021-10-15 10:46:35 -0700
> Engine • revision d3ea636dc5
> Tools • Dart 2.14.4
> ```
> 
> When I run flutter doctor from the Intellij terminal, I get the following for Intellij IDEA ultimate edition:
> 
> ```
> [☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
>     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
>     ✗ FormatException: Unexpected extension byte (at offset 5)
>     • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
>       #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
>       #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
>       #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
>       #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
>       #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
>       #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
>       #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
>       #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
>       #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
>       #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
>       #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
> ```
> 
> I cannot update any plugins anymore in Intellij, all plugins are up-to-date.

Same problem here

**Comment by AntoniosValais** [comment]
> Can it be that this issue still exists?
> 
> I'm running:
> 
>     * Intellij Ultimate 2021.3 Build #IU-213.5744.223, built on November 27, 2021
> 
>     * Flutter plugin 63.0.5
> 
>     * Dart plugin 213.5744.122
> 
>     * Flutter -v output:
> 
> 
> ```
> Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 18116933e7 (8 weeks ago) • 2021-10-15 10:46:35 -0700
> Engine • revision d3ea636dc5
> Tools • Dart 2.14.4
> ```
> 
> When I run flutter doctor from the Intellij terminal, I get the following for Intellij IDEA ultimate edition:
> 
> ```
> [☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
>     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
>     ✗ FormatException: Unexpected extension byte (at offset 5)
>     • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
>       #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
>       #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
>       #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
>       #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
>       #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
>       #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
>       #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
>       #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
>       #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
>       #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
>       #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
> ```
> 
> I cannot update any plugins anymore in Intellij, all plugins are up-to-date.

Same problem here

**Comment by tvkoz** [comment]
> Can it be that this issue still exists?
> 
> I'm running:
> 
>     * Intellij Ultimate 2021.3 Build #IU-213.5744.223, built on November 27, 2021
> 
>     * Flutter plugin 63.0.5
> 
>     * Dart plugin 213.5744.122
> 
>     * Flutter -v output:
> 
> 
> ```
> Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 18116933e7 (8 weeks ago) • 2021-10-15 10:46:35 -0700
> Engine • revision d3ea636dc5
> Tools • Dart 2.14.4
> ```
> 
> When I run flutter doctor from the Intellij terminal, I get the following for Intellij IDEA ultimate edition:
> 
> ```
> [☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
>     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
>     ✗ FormatException: Unexpected extension byte (at offset 5)
>     • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
>       #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
>       #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
>       #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
>       #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
>       #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
>       #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
>       #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
>       #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
>       #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
>       #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
>       #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
> ```
> 
> I cannot update any plugins anymore in Intellij, all plugins are up-to-date.

Same problem here.

It seems that once I disable all flutter/dart related plugins, the problem goes away, and comes back once I firstly install again the dart plugin

**Comment by westito** [comment]
Still not working. If I delete Dart.jar the exception gone.

**Comment by Lootwig** [comment]
This should be reopened, it is still/again an issue.

**Comment by HOWZ1T** [comment]
I am also getting this issue. I am using Intellij IDEA Ultimate, everything, including plugins, are up-to-date.
Note: I am on the dev channel of flutter but I get the same error in the stable channel as well.

Here is the output of `flutter doctor -v`:
```bash
[√] Flutter (Channel dev, 2.6.0-11.0.pre, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.6.0-11.0.pre at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (3 months ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\dylan\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\dylan\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5457.46
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:199:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>


[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\dylan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19042.1348]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 96.0.4664.93
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 93.0.961.52
```

**Comment by luisdeleon** [comment]
I am getting the same error as everyone else here:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about
this issue at https://github.com/flutter/flutter/issues.
✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by ryanawhelan** [comment]
I am still getting the error with 

Ubuntu Linux
IntelliJ IDEA 2021.3 (Ultimate Edition) 213.5744.223
Flutter plugin version 63.1.4
Both Flutter 2.5.3 and 2.8.0, same error message

flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on Ubuntu 20.04.3 LTS 5.4.0-91-generic, locale en_US.UTF-8)
    • Flutter version 2.8.0 at /home/x/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/x/Android/Sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /home/x/Android/Sdk
    • ANDROID_SDK_ROOT = /home/x/Android/Sdk
    • Java binary at: /home/x/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/x/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034
    • Flutter plugin version 63.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

**Comment by ryanawhelan** [comment]
@darshankawar  I had it crash after upgrading to 2021.3 but before upgrading to 2.8.0.  looks me like the crash is related to flutter_tools unzipping and trying to parse an XML file inside the  flutter-idea-xx.x.x.jar file.  The routines inside flutter_tools haven't changed in a while.

**Comment by darshankawar** [comment]
@ryanawhelan 
Thanks. We've reopened original issue to track this from flutter tool side. https://github.com/flutter/flutter/issues/94478 please follow-up in it.

**Comment by darshankawar** [comment]
There seems to be already an original issue to track, so please follow-up in https://github.com/flutter/flutter/issues/94060

**Comment by omidshojaee** [comment]
I also have this issue today.

IntelliJ IDEA community edition v2021.3 (Build #IC-213.5744.223, built on November 27, 2021)
Flutter plugin: 63.2.24
Flutter SDK: 2.8.0 Stable

**Comment by magicmike** [comment]
I am also still getting this today. Tried the update all my plugins proposed solution, it did not fix the issue.     
      
IntelliJ IDEA 2021.3 (Ultimate Edition)       
Build #IU-213.5744.223, built on November 27, 2021

**Comment by dev-whoan** [comment]
I downgrade IntelliJ From 2021.3 -> 2021.2.3 and now it works.

Flutter: 2.8.1 | 63.3.3 on IntelliJ
Dart    : 2.15.1 | 212.5632 on IntelliJ

**Comment by omidshojaee** [comment]
This is NOT a solution.

**Comment by luisdeleon** [comment]
Same here, and I agreed it's not a solution. 
Running IntelliJ IDEA 2021.3 Ultimate Edition
Flutter 2.8.1 with 63.2.4 plugin latest compatible version
and
Dart 2.15.1 with 213.574.122 plugin latest compatible version

**Comment by omidshojaee** [comment]
The issue is not resolved.

I have the latest available version of everything. What else I'm supposed to do?

![Screenshot 2021-12-27 135355](https://user-images.githubusercontent.com/31741561/147462706-b7a3cf32-097a-4205-92b5-7ce7ecbdcc51.png)

![Screenshot 2021-12-27 135445](https://user-images.githubusercontent.com/31741561/147462745-277b341f-a0a4-41b9-8db3-bf8711f70d50.png)

**Comment by mousedownmike** [comment]
@omidshojaee I think your best bet is to follow Flutter issue [#94060](https://github.com/flutter/flutter/issues/94060).  If you have to use IDEA, then you can roll back to an older version or if that's not critical, you can use Android Studio. That's what I've been doing and it's fine.

**Comment by minhuits** [comment]
It is recommended to additionally install IntelliJ IDEA 2021.1.3 Ultimate Edition. Then the error goes away.
![image](https://user-images.githubusercontent.com/58944350/148704271-c20d5223-8308-4c2d-b323-00f5d2711b9d.png)
![image](https://user-images.githubusercontent.com/58944350/148704348-655fd83e-4374-44f1-a79c-689418296a74.png)

**Comment by omidshojaee** [comment]
Rollback/Downgrade is not a SOLUTION.

**Comment by bernaferrari** [comment]
This issue is about flutter plugin not working at all. The flutter doctor issue is another one.

**Comment by Elio-Shyti** [comment]
I had the same problem and had to downgrade IntelliJ to 21.2.x to fix it.
I hope this problem to be fixed also you latest IntelliJ version.

**Comment by sergio-t** [comment]
I had the same problem 
Running IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (7 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
![2022-02-01_215940](https://user-images.githubusercontent.com/3526006/152042292-15be3d62-94ee-4f92-982c-f0d283d5acf6.jpg)

**Comment by jrb1989** [comment]
any update about this?

**Comment by akaushal123** [comment]
> 

@MarekBartczak solution worked for me.Thanks

**Comment by berkersal** [comment]
> flutter channel 'master' flutter upgrade
> 
> works for me on ubuntu and macos

Worked in Manjaro too

**Comment by altuntasfth** [comment]
> flutter channel 'master' flutter upgrade
> 
> works for me on ubuntu and macos

@MarekBartczak thanks for solution, worked ın mac m1.

**Comment by afustrator** [comment]
> flutter channel 'master' flutter upgrade
> 
> works for me on ubuntu and macos



> flutter channel 'master' flutter upgrade
> 
> works for me on ubuntu and macos

work on windows 10
