### ISSUE TITLE
[Embedded inspector] Unable to start until explicitly open the web-based DevTools

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#6611]
https://user-images.githubusercontent.com/15884415/217449977-bef88b01-1aa9-4be1-b767-0baf8356dae1.mp4

## Version info

```
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [版本 10.0.22000.1455], locale zh-CN)
    • Flutter version 3.3.10 on channel stable at X:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (8 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at X:\IDEs\apps\IDEA-U\ch-0\223.8617.56
    • Flutter plugin version 72.0.4
    • Dart plugin version 223.8617.8
```

**Comment by AlexV525** [comment]
[idea - copy.log](https://github.com/flutter/flutter-intellij/files/10685832/idea.-.copy.log)
[jxbrowser.log](https://github.com/flutter/flutter-intellij/files/10685834/jxbrowser.log)

**Comment by stevemessick** [comment]
To summarize the video, the issue is that the widget tree in the embedded DevTools does not get updated until the web-based DevTools is opened. Please let me know if that is incorrect.

@AlexV525 Did this just start to happen after updating the Flutter plugin to v72?

**Comment by AlexV525** [comment]
> @AlexV525 Did this just start to happen after updating the Flutter plugin to v72?

Yes it does, although I haven't try to downgrade yet. This is happening in every start and hot restart.

**Comment by stevemessick** [comment]
@helin24 Can you think of any change in 72 that would cause this? The only change to the inspector I see is catching an `UnsatisfiedLinkError`. I wonder if this could be a local configuration problem? I didn't see anything useful in the log files, but am glad to have them included.

**Comment by kenzieschmoll** [comment]
@DanTup have we seen similar reports of this in VS code? Could it have something to do with the pub root directories not being set (or being set at the wrong time) for the embedded version? @CoderDake

**Comment by DanTup** [comment]
The original report at https://github.com/flutter/devtools/issues/4989 seems like a similar issue (at least that it's initially empty, but it's not clear if opening the web app would've fixed it). Changing the port seemed to fix the issue so I concluded that was a caching issue.

Do we know if JavaScript errors would show up in the attached logs if they were occurring? If not, https://github.com/flutter/flutter-intellij/issues/6612 might be useful diagnosing this too.

**Comment by AlexV525** [comment]
> but it's not clear if opening the web app would've fixed it

Its top comment said the inspector in a browser is functioning. I guess it's the same as this one.

How can I modify the port that DevTools uses in IDEA? The Dart plugin doesn't have this option as I can see.
![image](https://user-images.githubusercontent.com/15884415/217980762-6057d60c-a0b2-4f66-9374-e24dadd0da76.png)

**Comment by helin24** [comment]
> Do we know if JavaScript errors would show up in the attached logs if they were occurring?

Anything from the console should show up in the idea.log file, but I don't see anything unusual in this case. 

@AlexV525 there isn't an option to change the port of DevTools in the plugin currently. You may be able to force the port to change by running two projects at once (the second app run would get the different port).

**Comment by AlexV525** [comment]
> You may be able to force the port to change by running two projects at once (the second app run would get the different port).

Let me try this one.

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/217982281-d9de6df7-cb9a-48a6-ab78-4ee1eb04fbb1.png)

I started another project first and it works fine, after that I start the current project which is still having the issue. I guess that's not related to ports, but I'll leave this until we can find a way to debug this. Or should I need to switch to VS Code to see if it can reproduce and find some logs?

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/217984031-c5713cf6-3d88-4f70-9043-b83a1889dcf6.png)

Switching to VS Code, the inspector is first shown as blank as well, then it somehow restarted and it works. The 404 address is http://127.0.0.1:9100/inspector/api/ping.

However, it doesn't help when switching back to IDEA.

**Comment by AlexV525** [comment]
(P.S. Only the Widget Tree window is malfunctioning, other actions are working when it's blank.)

**Comment by DanTup** [comment]
> Switching to VS Code, the inspector is first shown as blank as well, then it somehow restarted and it works. The 404 address is http://127.0.0.1:9100/inspector/api/ping.

That was also noted in #4989 and is fixed by #5016. Our understanding was that this error was not causing any real issues (it was just logged, and prevented some APIs that VS Code doesn't use anymore from working). If you're able to easily switch to Flutter `master` to test, it'd be interesting to know if the problem disappears.

Your original log says "DevTools version 2.20.1" but in your VS Code screenshot above it shows "DevTools version 2.15.1". Did you test these on different versions? (If not, I think you're getting a cached version in VS Code, and changing the port number may "fix" that, although I don't know if it'll fix the issue).

**Comment by AlexV525** [comment]
I'm away from that device currently, will provide more details when I back to it next week. :)

**Comment by AlexV525** [comment]
> Your original log says "DevTools version 2.20.1" but in your VS Code screenshot above it shows "DevTools version 2.15.1". Did you test these on different versions? (If not, I think you're getting a cached version in VS Code, and changing the port number may "fix" that, although I don't know if it'll fix the issue).

I don't manually choose versions so I think they are bundled. Changing the port does not fix the issue since I didn't find how the port work (the screenshot with the network didn't include the port I've set). However, using VS Code never runs into the same behavior again.
![image](https://user-images.githubusercontent.com/15884415/218636592-9f0c26f4-4b6d-41d9-8115-3c0cf0925132.png)

Can I manually choose the DevTools version to test?

**Comment by DanTup** [comment]
@AlexV525 sorry I should have mentioned that changing the DevTools port requires a restart/reload of VS Code. The DevTools server is kept alive in the background and always tries to use the same port number within a session (I've [added a note](https://github.com/Dart-Code/Dart-Code/commit/e94a97722f26783bcb3f77bdf272a7c96246b68a) to the setting for future).


> However, using VS Code never runs into the same behavior again.

Do you mean everything is working fine in VS Code now (but still broken in IntelliJ)?

**Comment by AlexV525** [comment]
> Do you mean everything is working fine in VS Code now (but still broken in IntelliJ)?

Yes. Now I was thinking maybe it's caused by the version of DevTools.

**Comment by AlexV525** [comment]
This is the console when opening the Chrome DevTools from IDEA.

![image](https://user-images.githubusercontent.com/15884415/218971896-2cf4ce92-cb46-4a53-a265-cfea7b8f52e9.png)

**Comment by DanTup** [comment]
Odd. If changing the port in VS Code fixed it, it sounds like it could've been cache-related. But then I would've expected forcing a new port in IntelliJ (by having multiple instances open) would do the same thing.

The page at https://jxbrowser-support.teamdev.com/docs/guides/cache.html lists locations for the cache for JxBrowser. It says on Windows it's at:

```
Users\<user_name>\AppData\Local\JxBrowser\browsercore-<version>\UserData\Cache\
```

Assuming you have that directory, does closing Android Studio, deleting the directory and then trying again make any difference?

**Comment by AlexV525** [comment]
I only have `Users\<user_name>\AppData\Local\JxBrowser\<version>` actually.

**Comment by DanTup** [comment]
@helin24 do you know if JxBrowser is storing a cache of web pages it accesses, and if so, where they are? (sounds like they're not at the path noted in the doc above, but I don't know if that means it's not caching, or they're perhaps just somewhere else?)

@AlexV525 out of interest, are you able to easily test on Flutter's `master` channel to see whether it still occurs? (https://github.com/flutter/devtools/pull/5016 fixes one of the errors noted above, although I didn't expect that error would lead to issues like this).

**Comment by AlexV525** [comment]
> @AlexV525 out of interest, are you able to easily test on Flutter's `master` channel to see whether it still occurs? ([flutter/devtools#5016](https://github.com/flutter/devtools/pull/5016) fixes one of the errors noted above, although I didn't expect that error would lead to issues like this).

Sorry but the project has even not been migrated to 3.7 which has compile exceptions. We're still migrating...

**Comment by DanTup** [comment]
@AlexV525 I'm not certain, but I wouldn't have expected this issue to be project-specific. I think using just using a new counter app _should_ behave the same way (although it's also useful to know if that doesn't seem to be the case).

**Comment by AlexV525** [comment]
To be clear, changing the port doesn't fix the problem in VS Code, it fixes itself after the first start before I change the code. Now the only visible difference would be the different versions of DevTools that the two plugins are using, which:
- IDEA is using 2.20.1
- Dart-Code is using 2.15.1

Can anyone identify the policy for using the specific version of DevTools?

**Comment by DanTup** [comment]
@AlexV525

> To be clear, changing the port doesn't fix the problem in VS Code, it fixes itself after the first start before I change the port,

I'm not sure I understand. Can you clarify in what situations it works, and which situations it does not?


> Now the only visible difference would be the different versions of DevTools that the two plugins are using

DevTools is bundled with the SDK so they should be the same as long as both editors are using the same SDK. If they are using the same SDK, then it does seem like there's some caching going on.

You can verify which Flutter SDK that VS Code is using by running the **Dart: Open Extension Log** command shortly after opening the project, then searching for "Flutter SDK:". You should be able to compare this to the SDK being used in IntelliJ shown in your screenshot further up.

**Comment by AlexV525** [comment]
> You can verify which Flutter SDK that VS Code is using by running the **Dart: Open Extension Log** command shortly after opening the project, then searching for "Flutter SDK:". You should be able to compare this to the SDK being used in IntelliJ shown in your screenshot further up.

![image](https://user-images.githubusercontent.com/15884415/220944818-589a784e-6e36-44d0-a0c3-be9e87e1bc97.png)
![image](https://user-images.githubusercontent.com/15884415/220944857-ba1b2960-1052-4d50-837b-0d7f6c69ff24.png)

> I'm not sure I understand. Can you clarify in what situations it works, and which situations it does not?

Here https://github.com/flutter/flutter-intellij/issues/6611#issuecomment-1425089084 is the first time I've switched to the VS Code, without changing the port. And it works after a short-term blank without hitting this again.

**Comment by helin24** [comment]
The cache location Danny suggested is the only cache folder I see with JX Browser, so I don't think there's much to do there. We may consider changing to using an incognito window in the plugin so that caching in between sessions of using the IDE won't be an issue. 

I changed my Flutter version to 3.3.10 and I'm able to reproduce this problem with a new project created from that SDK. Changing the query string of the URL doesn't make a difference, so I think this isn't a cache problem. Is there an alternative version of DevTools or some other step I could try to isolate what the problem could be?

**Comment by AlexV525** [comment]
I think we may need to figure out why the plugin is using unbundled versions of DevTools.

**Comment by helin24** [comment]
Oh yes, very weird...

I ran an app and the plugin accessed this address through the embedded window, which resulted in DevTools v2.20.1: http://127.0.0.1:9104/inspector?ide=IntelliJ-IDEA&backgroundColor=3c3f41&embed=true&fontSize=13.0&uri=http%3A%2F%2F127.0.0.1%3A62409%2FIyC_NAJWrfA%3D

Then I opened DevTools from the icon in the IntelliJ console (this opens a new browser tab), which resulted in DevTools v2.15.0, and this address: http://127.0.0.1:9104/inspector?ide=IntelliJ-IDEA&uri=http%3A%2F%2F127.0.0.1%3A62409%2FIyC_NAJWrfA%3D

They're using the same server, but I'm not sure where DevTools v2.20.1 comes from. The IDE starts one server for both of these instances using `dart devtools`. @kenzieschmoll or @DanTup do you have any ideas?

**Comment by DanTup** [comment]
@helin24 those two URLs you gave appear to be the same except for a few querystring parameters (`backgroundColor/embed/fontSize`). I can't think of a reason these would serve up different versions of DevTools except for caching. If you copy the url from the embedded window and load it in Chrome, what do you see? (I would expect you'd see the same version as you saw in Chrome with the other URL? which also makes me feel like this is Chrome and JxBrowser having different caches?)

**Comment by helin24** [comment]
I was expecting though, that if I used an adjusted query string (e.g. I tried changing the background color so that the `backgroundColor` param changed), that the cache would be circumvented and a new version would be found? But is changing the query string not cache busting? I'll try specifying the port in a custom plugin.

**Comment by helin24** [comment]
Ah using a much higher port number does work, so query string is not cache busting and this is actually a cache issue (unfortunately the cache location for Chromium is hard to find... not sure where mine is either). 

Is there any cost to not caching DevTools? I feel like caching has only caused problems.

**Comment by AlexV525** [comment]
Could it be the `embed` query that affects results?

**Comment by AlexV525** [comment]
When I opened the exact same URL in Chrome (with backgroundColor, fontSize, embed), it can be loaded correctly. The real embedded, however, never become normal when doing this. And the inspector in Chrome is using 2.15.0.

![image](https://user-images.githubusercontent.com/15884415/221333282-02f03e99-365e-4979-9a7d-cd497af15451.png)

**Comment by DanTup** [comment]
> Ah using a much higher port number does work, so query string is not cache busting and this is actually a cache issue (unfortunately the cache location for Chromium is hard to find... not sure where mine is either).

Yeah, the querystring will prevent caching of index.html, but not of the js files it loads (since they have the same URL/querystring regardless of what was on the index.html), or what the service worked is caching.

I think this issue is may be the same outstanding issue from https://github.com/flutter/devtools/issues/3896 (see @elliette's comment at https://github.com/flutter/devtools/issues/3896#issuecomment-1433441857).

> Is there any cost to not caching DevTools? I feel like caching has only caused problems.

I'm not sure - perhaps a question for @elliette. Usually caching would speed things up, but in this case both the cache and the non-cached version are likely coming from the users local disk, so (except for cases where DevTools is running on a remote server) I don't know if there is a benefit (does Chrome cache parsed/compiled JS or only the source file?).

**Comment by AlexV525** [comment]
Following the step in https://github.com/flutter/devtools/issues/1674#issuecomment-713705722 solves this.

**Comment by DanTup** [comment]
@AlexV525 thanks for confirming! I'd forgotten you could get to that in IntelliJ now the developer tools are available.

This does seem like a caching issue then, so let's close this as a dupe of https://github.com/flutter/devtools/issues/3896.

**Comment by helin24** [comment]
Is there much that would makes sense to do on the plugin side? I think I mentioned earlier that we could start always opening an incognito browser for embedding, but if there will be fix coming from DevTools then probably no need.

**Comment by stevemessick** [comment]
No, I think the proposal in the issue linked above should be enough.
