### ISSUE TITLE
Can't not see the varable's information at breakpoint 

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter-intellij#7228]
## Steps to Reproduce

Setup a breakPoint and see the info in var. But everytime will raise error in log console:
```
Cannot invoke "com.google.gson.JsonElement.isJsonPrimitive()" because "elem" is null
```

Here is the img:
<img src="https://github.com/flutter/flutter-intellij/assets/49340347/452d635c-352c-42d2-bc45-231a5bc57e05" width=700 />

## Version info

```
[!] Flutter (Channel stable/v3.3.8.xianyu, 3.3.9-0.0.pre.210, on macOS 14.1.2
    23B92 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.9-0.0.pre.210 on channel stable/v3.3.8.xianyu at
      /Users/wjr/flutter
    ! Upstream repository git@gitlab.alibaba-inc.com:ali-flutter/flutter.git is
      not a standard remote
    • Framework revision a1f0c4291a (6 weeks ago), 2024-01-12 15:32:44 +0800
    • Engine revision 7bc1415569
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Flutter download mirror http://aliuc-flutter-storage.alibaba.net/uc

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/wjr/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/wjr/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/wjr/Library/Android/sdk
    • Java binary at: /Library/Internet
      Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2023.1)
    • Android Studio at /Users/wjr/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

```

**Comment by shoxter** [comment]
Happening to us too.

**Comment by shoxter** [comment]
> I had the same problem

Did you fix it?

**Comment by Tecode** [comment]
I had the same problem

**Comment by plumhly** [comment]
me too

**Comment by AlaJ97** [comment]
I had the same problem

**Comment by zekunyan** [comment]
Same problem. So sad...

**Comment by luckysmg** [comment]
[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/14431146/flutter-intellij.zip)

Here is the plugin that seems works fine. Everybody can take this can install from disk to fallback

**Comment by luckysmg** [comment]
The version of the zip I uploaded should be  version `77.1.2`

**Comment by RhodesRamesh** [comment]
> [flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/14431146/flutter-intellij.zip)
> 
> Here is the plugin that seems works fine. Everybody can take this and install from disk to fallback

How do i use this ?, can someone please help me.

**Comment by trueAtom** [comment]
+1 
- Cannot invoke "com.google.gson.JsonElement.isJsonPrimitive()" because "elem" is null

Android Studio Iguana | 2023.2.1
Build #AI-232.10227.8.2321.11479570, built on February 21, 2024

**Comment by trueAtom** [comment]
> The version of the zip I uploaded should be version `77.1.2`

Plugin 'Flutter' (version '77.1.2') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is AI-232.10227.8

**Comment by trueAtom** [comment]
> > [flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/14431146/flutter-intellij.zip)
> > Here is the plugin that seems works fine. Everybody can take this and install from disk to fallback
> 
> How do i use this ?, can someone please help me.

<img width="927" alt="image" src="https://github.com/flutter/flutter-intellij/assets/6696342/cc7143a6-229b-4acd-9ca4-bc3721c964fc">

**Comment by RhodesRamesh** [comment]
> > > [flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/14431146/flutter-intellij.zip)
> > > Here is the plugin that seems works fine. Everybody can take this and install from disk to fallback
> > 
> > 
> > How do i use this ?, can someone please help me.
> 
> <img alt="image" width="927" src="https://private-user-images.githubusercontent.com/6696342/309278644-cc7143a6-229b-4acd-9ca4-bc3721c964fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDkyNzcsIm5iZiI6MTcwOTQ0ODk3NywicGF0aCI6Ii82Njk2MzQyLzMwOTI3ODY0NC1jYzcxNDNhNi0yMjliLTRhY2QtOWNhNC1iYzM3MjFjOTY0ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMDY1NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY5ZjM5NzVlYWM0YjU1NDFhNzEwMjcxZGI5MTBmZDg0NGM1YWI4ZGFkMGVmMjBlNTNjOTE4Zjk1M2Y5YzkzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wDcdjO9QOh7JHfpIOLAVNS452dg2m068DCx0CjW4DVc">

Thank you @trueAtom  👍

**Comment by jwren** [comment]
Thank you for the bug report.  I just pushed out a point release of the Flutter plugin which resolves the exception.  Please do reopen if you see this issue on any version over `78.2.x`.

**Comment by luckysmg** [comment]
Emm seems 78.2.x still have issue...


https://github.com/flutter/flutter-intellij/assets/49340347/3e6ea80d-c86a-40dd-b4dd-8e07e3139db0

**Comment by sergchil** [comment]
Unfortunately not fixed 😢

**Comment by trueAtom** [comment]
> Emm seems 78.2.x still have issue...

the same

**Comment by zekunyan** [comment]
This problem is really blocking coding debug, please...

**Comment by BlackStriker99** [comment]
i am also facing this same issue even after upgrading plugin to 78.2.1

**Comment by jwren** [comment]
Thank you all for the +1's, the escalation here helps prioritize issues to be fixed.  I thought that issue root cause as a NPE:

```
Cannot invoke "com.google.gson.JsonElement.isJsonPrimitive()" because "elem" is null
```

I am convinced that the NPE is fixed in the point release, but clearly it was not the root cause of the hanging in the debugger.  I'll continue troubleshoot.  The message:

```
Cannot invoke "org.dartlang.vm.service.element.InstanceRef.getType()" because "instanceRef" is null
```

Gives me the next place to look so thank you, but it may also not be the root cause.  If any additional relevant logs (`Help` > `Show Logs in Finder` > ....) are being printed, do include them here.

For any additional +1's on this issue, please include your OS, Flutter Version and Flutter Plugin version to help narrow my search.

**Comment by BlackStriker99** [comment]
@jwren Not sure if this is case for all, i am attaching my environment data here.

<img width="285" alt="Screenshot 2024-03-07 at 11 29 25 PM" src="https://github.com/flutter/flutter-intellij/assets/40071991/7d9f3718-d9fe-4bac-a129-5bffde645105">

<img width="517" alt="Screenshot 2024-03-07 at 11 28 56 PM" src="https://github.com/flutter/flutter-intellij/assets/40071991/79df09a7-28dc-40e5-8f59-a7138aa90679">

<img width="398" alt="Screenshot 2024-03-07 at 11 53 02 PM" src="https://github.com/flutter/flutter-intellij/assets/40071991/3d860fdf-98d3-40e8-91b4-7e6636189aa7">


i have two flutter projects 

first one is having old SDK 2.10.5  and i am facing issue in that project.

<img width="938" alt="Screenshot 2024-03-07 at 11 47 13 PM" src="https://github.com/flutter/flutter-intellij/assets/40071991/e4ea0e7e-8554-42d3-b00a-e8ec7d483cac">

Second one is having latest flutter sdk 3.19.2 and issue is not present in this project.

<img width="1332" alt="Screenshot 2024-03-07 at 11 48 38 PM" src="https://github.com/flutter/flutter-intellij/assets/40071991/c3b2ed60-2c23-4933-b8ba-c35dbc04e94a">

Also i don't know where i can find the Show Logs in Finder So i can not help you with that. hope this will help to debug it might be issue with the projects which are in old SDK.

**Comment by jwren** [comment]
The original issue that this bug was opened for was that the exception

```
Cannot invoke "com.google.gson.JsonElement.isJsonPrimitive()" because "elem" is null
```

was thrown when debugging, i.e. "But everytime will raise error in log console".  It was not obvious until other posts that debugging was blocked or otherwise negatively effected.

Is there anyone using the latest Dart/Flutter stable SDKs hitting this issue?

**Comment by jwren** [comment]
@elliette -- hit this DWDS error when trying to debug the above issue in IntelliJ Ultimate 2023.3, Chrome platform with Hello Flutter clicker app modified with some static members:

![image](https://github.com/flutter/flutter-intellij/assets/1533520/4868d5d0-115a-4eb2-a380-9001d324ec5c)

**Comment by ravi-uleeco** [comment]
I have same config as https://github.com/flutter/flutter-intellij/issues/7228#issuecomment-1984168490 @BlackStriker99.

I am facing the same problem.

**Comment by jwren** [comment]
I have been unsuccessful in getting a reproduction locally.

Has anyone hit this issue with a recent version of the Flutter Framework, i.e. after version `2.10`?  If so, does anyone have a small piece of code and breakpoint location to reproduce the issue?

**Comment by shoxter** [comment]
I am on 2.10.5; unfortunately, my project is much more complicated than a few lines so unless we could utilize that over a screenshare or something, I won't be of much assistance.

**Comment by vidyda** [comment]
I had the same problem

**Comment by Howard2595** [comment]
same

**Comment by ravi-uleeco** [comment]
Debugging is working fine with Android Studio Giraffe and Lower Versions, but not Working with the higher versions.

**Comment by jwren** [comment]
@ravi-uleeco  That matches my understanding of the issue here as we did not push to older versions of Android Studio.

**Comment by trueAtom** [comment]
Hello everyone, I updated flutter from 3.7.9 to 3.19.3 and the debugging issue was resolved.

<img width="495" alt="image" src="https://github.com/flutter/flutter-intellij/assets/6696342/42623658-a29e-43ac-a608-a8b2e2f48fe0">
<img width="836" alt="image" src="https://github.com/flutter/flutter-intellij/assets/6696342/cb21b6ac-3c12-4de1-bd04-56637815e70f">

**Comment by jwren** [comment]
Shout out to @trueAtom for validating before I was able to ping this issue.

Closing this issue now as obsolete, this issue was caused by the VM protocol removing an old protocol, and the Flutter Plugin following suite to remove/deprecate old API calls.  From what I can tell this issue was only encountered by projects on very old versions of the Flutter/ Dart SDKs.

... That said, I did have one last attempt to fix this for projects on older SDKs: https://github.com/flutter/flutter-intellij/pull/7282.  Thanks to @luckysmg who posted the error that lead to this fix.  I hope that others find what @trueAtom did and that the issue is resolved.

The latest release of the Flutter Plugin, `74.4.x` for both Iguana and Jellyfish (!) has this fix.
