### ISSUE TITLE
JetBrains IDE (IntelliJ) does not understand workspaces (always suggests to run pub get even when it's been run)

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#7623]
Tracking issue for https://github.com/dart-lang/sdk/issues/56380 in the flutter/flutter-intellij bug repo.

**Comment by AlexanderBartash** [comment]
https://youtrack.jetbrains.com/issue/IDEA-354613/Multiple-tool-windows-throw-IllegalStateException-access-contentManager-when-its-not-yet-available

**Comment by brian-superlist** [comment]
To add onto this: Tests also always run `flutter pub get` before executing the tests as well, slowing down test execution.

**Comment by sigurdm** [comment]
@helin24 is this on track? We'd love workspaces to work also in intellij with the release of dart 3.6.

Feel free to reach out if you need help with anything.

**Comment by sigurdm** [comment]
I tried to reproduce the issue

I used
* IntelliJ IDEA 2022.3.3 (Community Edition) 
* Dart plugin 223.8977
* Dart from Flutter 3.24.3 • channel stable 

Even in a non-workspace, I always have the button that suggests to run `pub get`.

Is there some other suggestion that is depending on the freshness of the resolution? 

<img width="1159" alt="image" src="https://github.com/user-attachments/assets/256f4e98-7af7-48e5-a9e2-a6bf24650b9f">

Also I tried loading the engine with the `third_party/dart/third_party/pkg/yaml` missing. I got an error from `pub get` (as expected) but I did not see the `java.lang.IllegalStateException:` - maybe there is some console I am missing.

**Comment by sigurdm** [comment]
> Is there some other suggestion that is depending on the freshness of the resolution?

I realized I was only using the dart plugin - not the flutter plugin.

>  maybe there is some console I am missing.

Ah - these logs come in the terminal when intellij is started from terminal...

Ok - still haven't reproduced exactly - but I'm getting closer...

**Comment by jwren** [comment]
Start of work that I believe will be sufficient: https://github.com/JetBrains/intellij-plugins/pull/933

**Comment by jwren** [comment]
Closing out since the PR has been pushed over to JetBrains.

**Comment by BenevidesLecontes** [comment]
Hi @jwren is this issue already fixed? Because I'm using the latest version of Intellij and de latest dev flutter plugin and i'm seeing this issue.
![IntelliJ IDEA 2024-12-15 10 31 37](https://github.com/user-attachments/assets/eb26c7c6-dc89-4513-8478-a59c2cf4a248)

**Comment by sbergmair** [comment]
> Hi [@jwren](https://github.com/jwren) is this issue already fixed? Because I'm using the latest version of Intellij and de latest dev flutter plugin and i'm seeing this issue. ![IntelliJ IDEA 2024-12-15 10 31 37](https://github.com/user-attachments/assets/eb26c7c6-dc89-4513-8478-a59c2cf4a248)

Same issue for me

**Comment by jwren** [comment]
@sbergmair Yes, I thought this was fixed with the latest versions of the Flutter and Dart Plugins.  Which version of the Flutter Plugin do you have installed.  Do you have a repro you can share.

**Comment by Autocrab** [comment]
IntelliJ IDEA 2024.3.2.2 (Community Edition)
Dart 243.23654.44
Flutter 83.0.4

Still reproducing

**Comment by NicolaVerbeeck** [comment]
I am also experiencing this issue.

IntelliJ IDEA 2024.3.3 (Ultimate Edition)
Dart 243.23654.44
Flutter 83.0.4

**Comment by sbergmair** [comment]
Issue is still there

Flutter plugin: `83.0.4`
IntelliJ IDEA Community Edition (version 2024.3.2)
Flutter (Channel stable, 3.27.2, on macOS 15.3.1 24D70 darwin-arm64)

**Comment by karroze** [comment]
Come on, guys, it's been 4 months 😄

**Comment by sigurdm** [comment]
@jwren - can you validate if this still reproduces?

**Comment by Mueco42** [comment]
@sigurdm - It still occurs for me.

Flutter plugin: 83.0.4
IntelliJ IDEA 2024.3.5 (Ultimate Edition) - Windows

**Comment by alextekartik** [comment]
@jwren I created a sample project (one flutter and one dart project in a workspace) here:
https://github.com/tekartikdev/publicexp/tree/flutter_intellij_issue_7623

You can simply open the `workspace_exp` folder in intellij (using #IU-243.26053.27 and latest dart/flutter plugins as of today), it keeps telling pub get has not been run (when opening the main.dart flutter file for example). It slows downs test as mentionned above and even screw suggestion sometimes as it always ask to to a pub get before any other actions.

Same thing happen with Android Studio

![Image](https://github.com/user-attachments/assets/3eb2a103-130a-41da-93fc-2982412e2a74)

**Comment by brian-superlist** [comment]
Perhaps more info: I have also been trying Cursor for the past few months and VSCode also:

1. Always suggests to run `pub get` 
2. Always runs `pub get` on tests.

Not sure if this is helpful info, but it may not be an IDE-specific problem and more of a general Dart issue.

**Comment by karroze** [comment]
This is absolutely insane that **critical** bug can not be fixed in more than half a year. Makes me question really hard why exactly have I purchased a license and why have I been a loyal client for over a decade. This is just sad

**Comment by LongXiangGuo** [comment]
Feature request: Adaptor for [workspaces](https://dart.dev/tools/pub/workspaces)

**Comment by jwren** [comment]
Thank you @alextekartik for the repo.  We'll push out the Flutter IJ plugin next week with this fix, https://github.com/flutter/flutter-intellij/pull/8428.

**Comment by karroze** [comment]
The fix indeed worked. After almost a year, I can finally stop abusing my poor MacBook with over a 100 packages big monorepo projects 😂👍

**Comment by karroze** [comment]
Nah, I was too fast to jump to that conclusion... it still does not work. Plugin version `87.1`

And this statement is beyond devious 🤨

> Additional work may be needed for non-flutter pubspecs (i.e. the Dart IJ plugin)

**Comment by ldt-fweichert** [comment]
Also still occurring for me, also on the current `87.1`

**Comment by btrautmann** [comment]
Yeah, we're seeing the same number of contexts we were seeing prior to this being closed/fixed.

**Comment by jwren** [comment]
Thank you for the feedback and apologies for the nuisance notification.  Given the cost of these extensions in the platform as well as the risk for false positives for this particular check, we are removing it for the time being, see https://github.com/flutter/flutter-intellij/issues/8481.

To pick up this fix, consider the dev channel of the Flutter IntelliJ plugin: https://github.com/flutter/flutter-intellij/blob/main/docs/Dev-Channel.md

**Comment by btrautmann** [comment]
> Thank you for the feedback and apologies for the nuisance notification. Given the cost of these extensions in the platform as well as the risk for false positives for this particular check, we are removing it for the time being, see [#8481](https://github.com/flutter/flutter-intellij/issues/8481).
> 
> To pick up this fix, consider the dev channel of the Flutter IntelliJ plugin: https://github.com/flutter/flutter-intellij/blob/main/docs/Dev-Channel.md

Just to clarify--is the expectation that my [comment here](https://github.com/flutter/flutter-intellij/issues/7623#issuecomment-2806306164) is being addressed at all with these changes? I understand that workspaces have impacted the display of when `pub get` can be run and that's the focus here, but it seems like none of the conversation here has been about the actual fact that workspaces don't even seem to be beneficial at all if you're using Intellij.

**Comment by karroze** [comment]
Another 6 months have passed. And we still don't have any solution to this problem. How exactly this is ok? This feature is critical and most definitely is NOT RESOLVED!
