### ISSUE TITLE
Code completion 'eats' paren and causes analysis error

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#858]
Follow these steps carefully:

1. Create new Flutter project
1. Wait for analysis to complete
1. Place cursor at the end of line 23 (`primarySwatch: Colors.blue,`)
1. Press Enter
1. Type `bri` and press Tab
1. Type `Bri` and press Tab
1. Type `.` and press Tab

=> IDE completes to `.dart` but in the process 'eats' the parenthesis that was on the line below casing the code to no longer pass analysis

**Comment by mit-mit** [comment]
Reproed on macOS with IDEA 2016.3 and on Windows with IDEA 2017.1

**Comment by mit-mit** [comment]
@alexander-doroshko any idea what is going on?

**Comment by alexander-doroshko** [comment]
Good catch! Pushed the fix in the Dart plugin.

**Comment by devoncarew** [comment]
@alexander-doroshko, just confirming that this is fixed in the Dart plugin?

**Comment by alexander-doroshko** [comment]
Yes, the fix will appear WebStrom only since 2017.1.2, but in the IntelliJ plugin it will appear earlier.

**Comment by mit-mit** [comment]
I still see this in IDEA 2017.1.2 with upgraded plugins. When will it appear there?

**Comment by alexander-doroshko** [comment]
Oops, sorry, my fix works only partly. And in case of a `new` expression inside other `new` expression it doesn't work (and here we have `new ThemeData` inside `new MaterialApp`). I'll fix it asap and publish the updated plugin.

**Comment by alexander-doroshko** [comment]
Should be ok now, please update the Dart plugin.

**Comment by mit-mit** [comment]
Thanks, that works great!
